[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "text_summarization"
version = "0.1.0"
description = "A text summarization python project"
readme = "README.md"
authors = [{ name = "Sushant Thpa", email = "momsryder8@gmail.com" }]
