artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ignestion
  source_URL : https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
  local_data_file: artifacts/data_ignestion/data.zip
  unzip_dir: artifacts/data_ignestion